services:
  database:
    image: postgres
    command:
    - -N 515
    environment:
      POSTGRES_DB: mv_filmlistmerger
      POSTGRES_USER: mediathekview
      POSTGRES_PASSWORD: mediathekview
    shm_size: 4GB
  
  fimlistmerger:
    image: mediathekview/filmlistmerger:0.0.1-SNAPSHOT
    depends_on:
      - database
    links:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/mv_filmlistmerger?useServerPrepStmts=true&cachePrepStmts=true&rewriteBatchedStatements=true
      SPRING_DATASOURCE_USERNAME: mediathekview
      SPRING_DATASOURCE_PASSWORD: mediathekview
      FILMLISTMERGER_INPUT_PATH: input
      FILMLISTMERGER_OUTPUT_FORMAT: NEW
      FILMLISTMERGER_OUTPUT_FILE: output/filmlist.json
      MANAGEMENT_METRICS_EXPORT_INFLUX_ENABLED: 'true'
      MANAGEMENT_METRICS_EXPORT_INFLUX_BUCKET: filmlistmerger
      MANAGEMENT_METRICS_EXPORT_INFLUX_ORG: mediathekview
      MANAGEMENT_METRICS_EXPORT_INFLUX_TOKEN: filmlistmerger
      MANAGEMENT_METRICS_EXPORT_INFLUX_URI: http://influx:8086
    volumes:
      - $PWD/input:/workspace/input:rw
      - $PWD/output:/workspace/output:rw

  influx:
    container_name: influx
    image: influxdb:alpine
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: filmlistmerger
      DOCKER_INFLUXDB_INIT_PASSWORD: filmlistmerger
      DOCKER_INFLUXDB_INIT_ORG: mediathekview
      DOCKER_INFLUXDB_INIT_BUCKET: filmlistmerger
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: filmlistmerger

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000