apiVersion: v1
kind: Namespace
metadata:
  name: mediathekview
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filmlistmerger-inputfiles-claim
  namespace: mediathekview
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filmlistmerger-database-claim
  namespace: mediathekview
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filmlistmerger-metrics-grafana-claim
  namespace: mediathekview
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: mediathekview
  name: filmlist-download
  labels:
    app: filmlistmerger
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: filmlist-downloader
              image: mediathekview/filmlistdownloader:v1.0.1
              env:
                - name: OUTPUT_PATH
                  value: /output
              volumeMounts:
                - mountPath: /output
                  name: filmlist-input
              imagePullPolicy: Always
          restartPolicy: OnFailure
          volumes:
            - name: filmlist-input
              persistentVolumeClaim:
                claimName: filmlistmerger-inputfiles-claim
---
apiVersion: v1
kind: Service
metadata:
  name: filmlistmerger-metrics
  namespace: mediathekview

spec:
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
    - name: influxdb
      protocol: TCP
      port: 8086
  selector:
    app: metrics
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: mediathekview
  name: filmlistmerger-metrics
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
        - name: influx
          image: influxdb:alpine
          ports:
            - containerPort: 8086
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: filmlistmerger
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: filmlistmerger
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: mediathekview
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: filmlistmerger
            - name : DOCKER_INFLUXDB_INIT_RETENTION
              value: 1w
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: filmlistmerger
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: filmlistmerger-metrics-grafana-claim
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: mediathekview
  name: filmlistmerger
  labels:
    app: filmlistmerger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filmlistmerger
  template:
    metadata:
      labels:
        app: filmlistmerger
    spec:
      containers:
        - name: filmlistmerger-database
          image: postgres
          args:
           - -c
           - max_connections=515
          env:
            - name: POSTGRES_DB
              value: mv_filmlistmerger
            - name: POSTGRES_USER
              value: mediathekview
            - name: POSTGRES_PASSWORD
              value: mediathekview
            - name: PGDATA
              value: /data
          volumeMounts:
            - mountPath: /dev/shm
              name: shared-memory
            - mountPath: /data
              name: filmlist-database
        - name: filmlistmerger
          image: mediathekview/filmlistmerger:0.0.1-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/mv_filmlistmerger?useServerPrepStmts=true&cachePrepStmts=true&rewriteBatchedStatements=true
            - name: SPRING_DATASOURCE_USERNAME
              value: mediathekview
            - name: SPRING_DATASOURCE_PASSWORD
              value: mediathekview
            - name: LOGGING_LEVEL_ROOT
              value: INFO
            - name: FILMLISTMERGER_INPUT_PATH
              value: input
            - name: FILMLISTMERGER_OUTPUT_FORMAT
              value: NEW
            - name: FILMLISTMERGER_OUTPUT_FILE
              value: output/filmlist.json
            - name: FILMLISTMERGER_DATABASE_STARTUP_TIMEOUT
              value: '60'
            - name: FILMLISTMERGER_DATABASE_STARTUP_ENABLED
              value: 'true'
            - name: MANAGEMENT_METRICS_EXPORT_INFLUX_ENABLED
              value: 'true'
            - name: MANAGEMENT_METRICS_EXPORT_INFLUX_BUCKET
              value: filmlistmerger
            - name: MANAGEMENT_METRICS_EXPORT_INFLUX_ORG
              value: mediathekview
            - name: MANAGEMENT_METRICS_EXPORT_INFLUX_TOKEN
              value: filmlistmerger
            - name: MANAGEMENT_METRICS_EXPORT_INFLUX_URI
              value: http://filmlistmerger-metrics:8086
          volumeMounts:
            - name: filmlist-input
              mountPath: /workspace/input
            - name: filmlist-output
              mountPath: /workspace/output
          imagePullPolicy: Always
      volumes:
        - name: filmlist-input
          persistentVolumeClaim:
            claimName: filmlistmerger-inputfiles-claim
        - name: filmlist-database
          persistentVolumeClaim:
            claimName: filmlistmerger-database-claim
        - name: filmlist-output
          emptyDir: { }
        - name: shared-memory
          emptyDir: { }
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: filmlistmerger-metrics-ingress
  namespace: mediathekview

spec:
  rules:
    - host: metrics.filmlistmerger.mediathekview.de
      http:
        paths:
          - path: /
            backend:
              serviceName: filmlistmerger-metrics
              servicePort: 3000