camel:
    component:
        metrics:
            enabled: true
    dataformat:
        jackson:
            auto-discover-object-mapper: true
    springboot:
        main-run-controller: true
    threadpool:
        max-pool-size: 40
        pool-size: 10

filmlistmerger:
    database:
        startup:
            enabled: true
            timeout: 10
    input:
        path: input
    output:
        file: output/filmliste.json
        format: NEW

logging:
    level:
        liquibase: WARN
        org:
            apache:
                camel: INFO
        root: INFO

management:
    endpoint:
        camelroutes:
            enabled: true
        configprops:
            enabled: false
        env:
            enabled: false
        logfile:
            enabled: true
        metrics:
            enabled: true
    influx:
        metrics:
            export:
                enabled: false

spring:
    datasource:
        hikari:
            maximum-pool-size: 500
        password: filmlistmerger
        url: jdbc:postgresql://localhost:5432/filmlistmerger?useServerPrepStmts=true&cachePrepStmts=true&rewriteBatchedStatements=true
        username: filmlistmerger
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                jdbc:
                    batch_size: 30
                    batch_versioned_data: true
                order_inserts: true
                order_updates: true
    liquibase:
        change-log: classpath:db/changelog/master.xml
    test:
        database:
            replace: none
