@startuml
'https://plantuml.com/activity-diagram-beta
skinparam conditionStyle diamond
|Main|
start
:InputFilesRoute;
:SwitchOnFilmlistFormatRoute;
split
    |Old format|
    :ReadOldFilmlistFormatRoute;
split again
    |New format|
    :ReadNewFilmlistFormatRoute;
split again
    |Unknown format|
    stop
end split
|Main|
:FilmToDatabaseTargetRoute;
stop
@enduml
