name: Build and test snapshot

on:
  push:
    branches:
      - "master"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build and test with Maven
      run: ./mvnw -B package -Pdocker
    - name: Archive executable jar
      uses: actions/upload-artifact@v2
      with:
        name: application-jar
        path: target/filmlistmerger-*.jar
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push container
      run: docker push -a mediathekview/filmlistmerger
